sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 8.130.89.203
    port: 3306
    database: sky_take_out
    username: root
    password: BUzhidao520@
  redis:
    host: 8.130.89.203
    port: 6379
    password: root
  wechat:
    appid: wxa9708ea297d44d58
    secret: 9f4b61b608cf034d50381c61e20fd87f
