sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 8.130.89.203
    port: 3306
    database: sky_take_out
    username: root
    password: BUzhidao520@
  redis:
    host: 8.130.89.203
    port: 6379
    password: root
